[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/liwan"]

[workspace.package]
version = "1.6.0"
edition = "2024"
rust-version = "1.98"
homepage = "https://liwan.dev"
repository = "https://github.com/explodingcamera/liwan"
license = "Apache-2.0"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
debug = false
strip = true
lto = "thin"
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
strip = false
