# The base URL of the Liwan instance
base_url="http://localhost:8080"

# The port to listen on (http)
port=8080

# Folder to store the database in (Will be created if it doesn't exist)
db_dir="./liwan-db"

# GeoIp settings (Optional)
[geoip]
# maxmind_account_id="MY_ACCOUNT_ID"
# maxmind_license_key="MY_LICENSE_KEY"
# maxmind_edition="GeoLite2-City"

# # If you don't want to automatically download the database, you can specify a path to a local file
# maxmind_db_path="./GeoLite2-City.mmdb"
