FROM gcr.io/distroless/static-debian13:nonroot
ARG TARGETARCH

ENV LIWAN_CONFIG=/liwan.config.toml
ENV LIWAN_DATA_DIR=/data

USER 1000:1000

COPY ./dist/${TARGETARCH}/liwan /liwan
COPY --chown=1000:1000 ./dist/data /data
VOLUME /data

EXPOSE 9042
STOPSIGNAL SIGINT
ENTRYPOINT ["/liwan"]