name: Release

on:
  push:
    tags:
      - liwan-v[0-9]+.*

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: taiki-e/create-gh-release-action@c5baa0b5dc700cf06439d87935e130220a6882d9 # v1.9.3
        with:
          changelog: CHANGELOG.md
          allow-missing-changelog: true
          draft: false # has to be public to have the right url's for the docker image
          prefix: liwan
          token: ${{ secrets.GITHUB_TOKEN }}

  build-web:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@ecf28ddc73e819eb6fa29df6b34ef8921c743461 # v2.1.3
        with:
          bun-version: latest
          no-cache: true
      - name: Build web project
        run: |
          bun install
          bun run build
        working-directory: ./web
      - name: Upload web assets
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: web-dist
          path: ./web/dist

  upload-assets:
    permissions:
      contents: write
    needs: [create-release, build-web]
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
            build-tool: cargo-zigbuild
          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04
            build-tool: cargo-zigbuild
          - target: aarch64-apple-darwin
            os: macos-latest
            build-tool: cargo

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: web-dist
          path: ./web/dist
      - uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3
        with:
          cache: false
      - uses: taiki-e/upload-rust-binary-action@381995c84a8e242b8736ec80211c563d7bd07ce7 # v1.28.1
        with:
          bin: liwan
          target: ${{ matrix.target }}
          build-tool: ${{ matrix.build-tool }}
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-container:
    permissions:
      packages: write
      contents: read
    needs: [create-release, upload-assets]
    uses: explodingcamera/liwan/.github/workflows/container.yaml@main
    with:
      tag: ${{ github.ref_name }}
