name: Run tests (web)

on:
  pull_request:
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "bun.lock"
      - "packages/**/package.json"
  push:
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "bun.lock"
      - "packages/**/package.json"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest
      - name: Install workspace dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Run tests
        run: bun test
      - name: Run typecheck
        run: bun typecheck
